#pragma once

#define SCREEN_WIDTH_LANDSCAPE 400
#define SCREEN_HEIGHT_LANDSCAPE 240

#define SCREEN_WIDTH_PORTRAIT 240
#define SCREEN_HEIGHT_PORTRAIT 400

#define PORTRAIT 0
#define LANDSCAPE 1

#define VIEW_MODE PORTRAIT